[general]
import = ["~/.cache/wal/colors-alacritty.toml"]

[window]
opacity = 0.9
padding = { x = 20, y = 20 }

[font]
size = 16.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[cursor]
style = { blinking = "On" }
