# Helix Theme Template using Material You with improved contrast

# --- Syntax Elements ---

"attribute" = "#c4cd7b"
"type" = "#c7c9a6"
"type.enum.variant" = "#c7c9a6"
"constructor" = "#e0e994"

"constant" = "#a2d0c1"
"constant.character" = "#a2d0c1"
"constant.character.escape" = "#234e43"

"string" = "#c4cd7b"
"string.regexp" = "#234e43"
"string.special" = "#e0e994"
"string.special.symbol" = "#ffb4ab"

"comment" = { fg = "#c8c7b7", modifiers = ["italic"] }

"variable" = "#e5e3d6"
"variable.parameter" = { fg = "#93000a", modifiers = ["italic"] }
"variable.builtin" = "#ffb4ab"
"variable.other.member" = "#c4cd7b"

"label" = "#e0e994"

"punctuation" = "#c8c7b7"
"punctuation.special" = "#c7c9a6"

"keyword" = "#c4cd7b"
"keyword.control.conditional" = { fg = "#c4cd7b", modifiers = ["italic"] }

"operator" = "#c7c9a6"

"function" = "#c4cd7b"
"function.macro" = "#444b04"

"tag" = "#c4cd7b"
"namespace" = { fg = "#c7c9a6", modifiers = ["italic"] }

"special" = "#c4cd7b"

# --- Markup ---

"markup.heading.1" = "#ffb4ab"
"markup.heading.2" = "#c4cd7b"
"markup.heading.3" = "#c7c9a6"
"markup.heading.4" = "#a2d0c1"
"markup.heading.5" = "#e0e994"
"markup.heading.6" = "#444b04"

"markup.list" = "#c7c9a6"
"markup.list.unchecked" = "#c8c7b7"
"markup.list.checked" = "#e0e994"

"markup.bold" = { fg = "#c4cd7b", modifiers = ["bold"] }
"markup.italic" = { fg = "#c7c9a6", modifiers = ["italic"] }

"markup.link.url" = { fg = "#c4cd7b", modifiers = ["italic", "underlined"] }
"markup.link.text" = "#e0e994"
"markup.link.label" = "#a2d0c1"
"markup.raw" = "#beecdd"
"markup.quote" = "#234e43"

# --- Diff ---

"diff.plus" = "#a2d0c1"
"diff.minus" = "#ffb4ab"
"diff.delta" = "#c4cd7b"

# --- UI Elements ---

"ui.background" = { fg = "#e5e3d6", bg = "none" }

"ui.linenr" = { fg = "#c8c7b7" }
"ui.linenr.selected" = { fg = "#e0e994" }

"ui.statusline" = { fg = "#e0e994", bg = "none" }
"ui.statusline.inactive" = { fg = "#c8c7b7", bg = "none" }
"ui.statusline.normal" = { fg = "#13140d", bg = "none", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "#13140d", bg = "none", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "#13140d", bg = "none", modifiers = ["bold"] }

"ui.popup" = { fg = "#e5e3d6", bg = "none" }
"ui.window" = { fg = "#c8c7b7" }
"ui.help" = { fg = "#c8c7b7", bg = "none" }

"ui.bufferline" = { fg = "#c8c7b7", bg = "none" }
"ui.bufferline.active" = { fg = "#2e3300", bg = "#c4cd7b", underline = { color = "#c4cd7b", style = "line" } }
"ui.bufferline.background" = { bg = "none" }

"ui.text" = "#e5e3d6"
"ui.text.focus" = { fg = "#c4cd7b", bg = "none", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "#c8c7b7" }
"ui.text.directory" = { fg = "#c4cd7b" }

"ui.virtual" = "#c8c7b7"
"ui.virtual.ruler" = { bg = "none" }
"ui.virtual.indent-guide" = "#1c1c14"
"ui.virtual.inlay-hint" = { fg = "#c8c7b7", bg = "none" }
"ui.virtual.jump-label" = { fg = "#444b04", modifiers = ["bold"] }

"ui.selection" = { bg = "#46492e" }

"ui.cursor" = { fg = "#13140d", bg = "#e0e994" }
"ui.cursor.primary" = { fg = "#13140d", bg = "#e0e994" }
"ui.cursor.match" = { fg = "#e0e994", modifiers = ["bold"] }

"ui.highlight" = { bg = "#46492e", modifiers = ["bold"] }

"ui.menu" = { fg = "#e5e3d6", bg = "none" }
"ui.menu.selected" = { fg = "#c4cd7b", bg = "none", modifiers = ["bold"] }

# --- Diagnostics ---

"diagnostic.error" = { fg = "#ffb4ab", underline = { color = "#ffb4ab", style = "curl" } }
"diagnostic.warning" = { fg = "#c7c9a6", underline = { color = "#c7c9a6", style = "curl" } }
"diagnostic.info" = { fg = "#a2d0c1", underline = { color = "#a2d0c1", style = "curl" } }
"diagnostic.hint" = { fg = "#234e43", underline = { color = "#234e43", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
