# Helix Theme Template using Material You with improved contrast

# --- Syntax Elements ---

"attribute" = "#d8c76f"
"type" = "#d0c7a2"
"type.enum.variant" = "#d0c7a2"
"constructor" = "#f6e388"

"constant" = "#a8d0b5"
"constant.character" = "#a8d0b5"
"constant.character.escape" = "#2a4e39"

"string" = "#d8c76f"
"string.regexp" = "#2a4e39"
"string.special" = "#f6e388"
"string.special.symbol" = "#ffb4ab"

"comment" = { fg = "#ccc6b5", modifiers = ["italic"] }

"variable" = "#e8e2d4"
"variable.parameter" = { fg = "#93000a", modifiers = ["italic"] }
"variable.builtin" = "#ffb4ab"
"variable.other.member" = "#d8c76f"

"label" = "#f6e388"

"punctuation" = "#ccc6b5"
"punctuation.special" = "#d0c7a2"

"keyword" = "#d8c76f"
"keyword.control.conditional" = { fg = "#d8c76f", modifiers = ["italic"] }

"operator" = "#d0c7a2"

"function" = "#d8c76f"
"function.macro" = "#524700"

"tag" = "#d8c76f"
"namespace" = { fg = "#d0c7a2", modifiers = ["italic"] }

"special" = "#d8c76f"

# --- Markup ---

"markup.heading.1" = "#ffb4ab"
"markup.heading.2" = "#d8c76f"
"markup.heading.3" = "#d0c7a2"
"markup.heading.4" = "#a8d0b5"
"markup.heading.5" = "#f6e388"
"markup.heading.6" = "#524700"

"markup.list" = "#d0c7a2"
"markup.list.unchecked" = "#ccc6b5"
"markup.list.checked" = "#f6e388"

"markup.bold" = { fg = "#d8c76f", modifiers = ["bold"] }
"markup.italic" = { fg = "#d0c7a2", modifiers = ["italic"] }

"markup.link.url" = { fg = "#d8c76f", modifiers = ["italic", "underlined"] }
"markup.link.text" = "#f6e388"
"markup.link.label" = "#a8d0b5"
"markup.raw" = "#c4ecd0"
"markup.quote" = "#2a4e39"

# --- Diff ---

"diff.plus" = "#a8d0b5"
"diff.minus" = "#ffb4ab"
"diff.delta" = "#d8c76f"

# --- UI Elements ---

"ui.background" = { fg = "#e8e2d4", bg = "none" }

"ui.linenr" = { fg = "#ccc6b5" }
"ui.linenr.selected" = { fg = "#f6e388" }

"ui.statusline" = { fg = "#f6e388", bg = "none" }
"ui.statusline.inactive" = { fg = "#ccc6b5", bg = "none" }
"ui.statusline.normal" = { fg = "#15130c", bg = "none", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "#15130c", bg = "none", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "#15130c", bg = "none", modifiers = ["bold"] }

"ui.popup" = { fg = "#e8e2d4", bg = "none" }
"ui.window" = { fg = "#ccc6b5" }
"ui.help" = { fg = "#ccc6b5", bg = "none" }

"ui.bufferline" = { fg = "#ccc6b5", bg = "none" }
"ui.bufferline.active" = { fg = "#383000", bg = "#d8c76f", underline = { color = "#d8c76f", style = "line" } }
"ui.bufferline.background" = { bg = "none" }

"ui.text" = "#e8e2d4"
"ui.text.focus" = { fg = "#d8c76f", bg = "none", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "#ccc6b5" }
"ui.text.directory" = { fg = "#d8c76f" }

"ui.virtual" = "#ccc6b5"
"ui.virtual.ruler" = { bg = "none" }
"ui.virtual.indent-guide" = "#1e1c13"
"ui.virtual.inlay-hint" = { fg = "#ccc6b5", bg = "none" }
"ui.virtual.jump-label" = { fg = "#524700", modifiers = ["bold"] }

"ui.selection" = { bg = "#4d472b" }

"ui.cursor" = { fg = "#15130c", bg = "#f6e388" }
"ui.cursor.primary" = { fg = "#15130c", bg = "#f6e388" }
"ui.cursor.match" = { fg = "#f6e388", modifiers = ["bold"] }

"ui.highlight" = { bg = "#4d472b", modifiers = ["bold"] }

"ui.menu" = { fg = "#e8e2d4", bg = "none" }
"ui.menu.selected" = { fg = "#d8c76f", bg = "none", modifiers = ["bold"] }

# --- Diagnostics ---

"diagnostic.error" = { fg = "#ffb4ab", underline = { color = "#ffb4ab", style = "curl" } }
"diagnostic.warning" = { fg = "#d0c7a2", underline = { color = "#d0c7a2", style = "curl" } }
"diagnostic.info" = { fg = "#a8d0b5", underline = { color = "#a8d0b5", style = "curl" } }
"diagnostic.hint" = { fg = "#2a4e39", underline = { color = "#2a4e39", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
